import {
  ALL_PERMISSION_CODES,
  SYSTEM_ROLE_CODES,
  type SystemRoleCode,
} from "@/domain/policies/permissions";

export type SeedRoleDefinition = {
  code: SystemRoleCode;
  name: string;
  description: string;
  isSystem: true;
  globalRead: boolean;
  /** Permission codes granted. Use "*" for all. */
  permissions: string[] | "*";
};

function codesMatching(...prefixes: string[]) {
  return ALL_PERMISSION_CODES.filter((code) =>
    prefixes.some((prefix) => code === prefix || code.startsWith(`${prefix}.`) || code.startsWith(prefix)),
  );
}

function pick(...codes: string[]) {
  return codes.filter((code) => ALL_PERMISSION_CODES.includes(code));
}

/** Default system role grants — tuned from docs/07 role capability summary. */
export const SEED_ROLES: SeedRoleDefinition[] = [
  {
    code: SYSTEM_ROLE_CODES.SUPER_ADMIN,
    name: "Super Admin",
    description: "Full platform access. Irreversible system role.",
    isSystem: true,
    globalRead: true,
    permissions: "*",
  },
  {
    code: SYSTEM_ROLE_CODES.ADH,
    name: "ADH",
    description: "Org-wide oversight, directives, high-level approvals.",
    isSystem: true,
    globalRead: true,
    permissions: pick(
      ...codesMatching("users", "roles", "permissions", "org", "audit", "projects", "houses", "contractors", "employees", "boq", "activities", "ir", "dpr", "wpr", "mb", "bills", "payments", "budgets", "directives", "documents", "notifications", "inbox", "reports", "dashboards", "settings"),
      "workflow.manage",
      "workflow.delegate",
      "search.use",
    ),
  },
  {
    code: SYSTEM_ROLE_CODES.AD_TECH,
    name: "AD Tech",
    description: "Technical masters: BOQ, activities, house types, reports.",
    isSystem: true,
    globalRead: true,
    permissions: pick(
      "projects.read",
      "phases.manage",
      "sectors.manage",
      "blocks.manage",
      "house_types.manage",
      "houses.read",
      "houses.create",
      "houses.update",
      "houses.import",
      ...codesMatching("boq", "activities"),
      "materials.read",
      "materials.manage",
      "reports.read",
      "reports.export",
      "dashboards.read",
      "documents.read",
      "documents.manage",
      "search.use",
    ),
  },
  {
    code: SYSTEM_ROLE_CODES.RESIDENT_ENGINEER,
    name: "Resident Engineer",
    description: "Project operations: houses, IR/DPR/WPR/MB, contractor coordination.",
    isSystem: true,
    globalRead: false,
    permissions: pick(
      "projects.read",
      "projects.members",
      "houses.read",
      "houses.create",
      "houses.update",
      "houses.status",
      "contractors.read",
      "contractors.assign",
      "employees.read",
      "employees.assign",
      ...codesMatching("boq.read", "activities", "ir", "dpr", "wpr", "mb"),
      "mr.read",
      "mr.approve",
      "issue.read",
      "consumption.read",
      "directives.read",
      "directives.acknowledge",
      "documents.read",
      "documents.upload",
      "inbox.read",
      "inbox.act",
      "reports.read",
      "dashboards.read",
      "notifications.read",
      "search.use",
    ),
  },
  {
    code: SYSTEM_ROLE_CODES.QUALITY_MANAGER,
    name: "Quality Manager",
    description: "IR review/approve and quality reporting.",
    isSystem: true,
    globalRead: false,
    permissions: pick(
      "projects.read",
      "houses.read",
      ...codesMatching("ir"),
      "activities.read",
      "boq.read",
      "dpr.read",
      "wpr.read",
      "documents.read",
      "documents.upload",
      "reports.read",
      "reports.export",
      "dashboards.read",
      "inbox.read",
      "inbox.act",
      "notifications.read",
      "search.use",
    ),
  },
  {
    code: SYSTEM_ROLE_CODES.CONTRACTOR,
    name: "Contractor",
    description: "Limited project access; IR/DPR create/submit; own bills.",
    isSystem: true,
    globalRead: false,
    permissions: pick(
      "projects.read",
      "houses.read",
      "activities.read",
      "boq.read",
      "ir.read",
      "ir.create",
      "ir.submit",
      "dpr.read",
      "dpr.create",
      "dpr.submit",
      "wpr.read",
      "mb.read",
      "bills.read",
      "bills.create",
      "bills.submit",
      "documents.read",
      "documents.upload",
      "directives.read",
      "directives.acknowledge",
      "inbox.read",
      "inbox.act",
      "notifications.read",
      "dashboards.read",
      "search.use",
    ),
  },
  {
    code: SYSTEM_ROLE_CODES.CONTRACTOR_ENGINEER,
    name: "Contractor Engineer",
    description: "Site execution: progress, IR, DPR lines.",
    isSystem: true,
    globalRead: false,
    permissions: pick(
      "projects.read",
      "houses.read",
      "houses.update",
      "activities.read",
      "boq.read",
      "ir.read",
      "ir.create",
      "ir.submit",
      "dpr.read",
      "dpr.create",
      "dpr.submit",
      "wpr.read",
      "wpr.create",
      "wpr.submit",
      "documents.read",
      "documents.upload",
      "inbox.read",
      "notifications.read",
      "search.use",
    ),
  },
  {
    code: SYSTEM_ROLE_CODES.STORE_OFFICER,
    name: "Store Officer",
    description: "Warehouses, GRN, issue, returns, ledger, MR/DV fulfill.",
    isSystem: true,
    globalRead: false,
    permissions: pick(
      "projects.read",
      ...codesMatching(
        "warehouses",
        "materials",
        "grn",
        "mr",
        "dv",
        "issue",
        "consumption",
        "returns",
        "ledger",
        "stock",
      ),
      "houses.read",
      "documents.read",
      "documents.upload",
      "inbox.read",
      "inbox.act",
      "notifications.read",
      "reports.read",
      "search.use",
    ),
  },
  {
    code: SYSTEM_ROLE_CODES.FINANCE,
    name: "Finance",
    description: "Bills, payments, budgets, financial reports.",
    isSystem: true,
    globalRead: true,
    permissions: pick(
      "projects.read",
      ...codesMatching("bills", "payments", "budgets", "period", "retention"),
      "mb.read",
      "contractors.read",
      "documents.read",
      "documents.upload",
      "reports.read",
      "reports.export",
      "dashboards.read",
      "audit.read",
      "inbox.read",
      "inbox.act",
      "notifications.read",
      "search.use",
    ),
  },
  {
    code: SYSTEM_ROLE_CODES.SITE_SUPERVISOR,
    name: "Site Supervisor",
    description: "DPR/WPR create, MR create, consumption, house progress.",
    isSystem: true,
    globalRead: false,
    permissions: pick(
      "projects.read",
      "houses.read",
      "houses.update",
      "houses.status",
      "activities.read",
      "dpr.read",
      "dpr.create",
      "dpr.submit",
      "wpr.read",
      "wpr.create",
      "wpr.submit",
      "mr.read",
      "mr.create",
      "mr.submit",
      "consumption.read",
      "consumption.create",
      "consumption.submit",
      "issue.read",
      "ir.read",
      "ir.create",
      "documents.read",
      "documents.upload",
      "inbox.read",
      "notifications.read",
      "dashboards.read",
      "search.use",
    ),
  },
  {
    code: SYSTEM_ROLE_CODES.SENIOR_MANAGEMENT,
    name: "Senior Management",
    description: "Dashboards, reports, directives read, audit read — no operational post.",
    isSystem: true,
    globalRead: true,
    permissions: pick(
      "projects.read",
      "houses.read",
      "contractors.read",
      "employees.read",
      "boq.read",
      "activities.read",
      "ir.read",
      "dpr.read",
      "wpr.read",
      "mb.read",
      "bills.read",
      "payments.read",
      "budgets.read",
      "ledger.read",
      "directives.read",
      "documents.read",
      "reports.read",
      "reports.export",
      "dashboards.read",
      "audit.read",
      "notifications.read",
      "inbox.read",
      "search.use",
    ),
  },
];
